### ISSUE TITLE
Issue with spell engine config

### ISSUE THREAD

**Issue by NathanWSpaghetti** [ZsoltMolnarrr/CombatSpells#91] opened 2024-12-20 18:08 UTC
server starts up fine, but when joining in on client-side, the server produces this message to the user, and on the server:
"network configuration task not supported: spell_engine:config"

I should note, there is 40+ mods, and I am using Neoforge with a fabric connector

**Comment by ZsoltMolnarrr** [comment] 2024-12-21 01:19
Duplicate of #80.
Awaiting fix from Connector team.

**Closed as completed by ZsoltMolnarrr** 2024-12-21 01:19 UTC
