### ISSUE TITLE
Crash on Spell Engine 1.19.2 Fabric 0.14.21

### ISSUE THREAD

**Issue by pokesmells** [ZsoltMolnarrr/CombatSpells#19] opened 2023-07-10 00:37 UTC
https://mclo.gs/eiOSXgF

Crash when using the spell table

**Comment by ZsoltMolnarrr** [comment] 2023-07-11 21:22
Cannot reproduce the issue.
Seems like you have multiple packet manipulation mods installed.
Also, the server and client seem to have an inconsistent amount of spell books. This can be a result of some data manipulation.
Please provide specific details about how to reproduce this issue.

**Comment by Odaghast** [comment] 2023-07-17 20:57
I received the same ( or at least very similar ) crash when shift + clicking a book out of the Spellbinding Table. I have yet to test this in a clean environment but I believe its due to vanillas quick stack moving leaving strange items stack values behind.

**Comment by ZsoltMolnarrr** [comment] 2023-07-17 22:17
Can this issue be replicated consistently, or does it happen completely randomly?

**Comment by ZsoltMolnarrr** [comment] 2023-07-19 20:32
Should be fixed by next update.

**Closed as completed by ZsoltMolnarrr** 2023-07-19 20:32 UTC
