### ISSUE TITLE
Does not connect to the server 1.21.1

### ISSUE THREAD

**Issue by Beshudar** [ZsoltMolnarrr/CombatSpells#89] opened 2024-12-04 09:13 UTC
When logging into the server, the error "Network configuration task not supported: spell_engine:config" occurs.

Neoforge Version: 21.1.83
Sinytra Connector Version: 2.0.0-beta.4+1.21.1

Please tell me how I can solve this problem.

![image](https://github.com/user-attachments/assets/66e220e6-76dd-4bf8-94f2-612ed5b2523a)

Thank you in advance!

**Comment by ZsoltMolnarrr** [comment] 2024-12-08 21:51
Duplicate of #80

**Closed as completed by ZsoltMolnarrr** 2024-12-08 21:51 UTC
