### ISSUE TITLE
crash when loading saved world (1.20.1)

### ISSUE THREAD

**Issue by netcore10** [ZsoltMolnarrr/CombatSpells#53] opened 2024-03-31 21:21 UTC
https://mclo.gs/qSKz34M
[crash-2024-03-31_22.20.39-client.txt](https://github.com/ZsoltMolnarrr/SpellEngine/files/14817654/crash-2024-03-31_22.20.39-client.txt)

**Comment by ZsoltMolnarrr** [comment] 2024-04-01 08:17
I am unable to reproduce such crash.

Could you specify which is the absolute minimum set of mods to reproduce this? 

Or is there a specific inventory setup that causes this?

**Comment by ZsoltMolnarrr** [comment] 2024-04-02 17:04
The crash is likely caused by another mod.
Make sure to update all of your mods. Closing the issue.

**Closed as completed by ZsoltMolnarrr** 2024-04-02 17:04 UTC
